displayName: State Block Middleware
type: middleware
import: github.com/vikewoods/traefik-plugin-state-geo

summary: Blocks requests based on US state.

testData:
  blockedStates:
    - CA
    - NY
  whitelistedIPs:
    - 1.2.3.4
    - 192.168.1.1